object Frm_InputLoan: TFrm_InputLoan
  Left = 330
  Top = 237
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Cash Advance'
  ClientHeight = 241
  ClientWidth = 553
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Calibri'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 15
  object RzGroupBox1: TRzGroupBox
    Left = 0
    Top = 0
    Width = 553
    Height = 241
    Align = alClient
    Caption = 'Cash Advance'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Calibri'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    VisualStyle = vsGradient
    object RzPanel1: TRzPanel
      Left = 1
      Top = 24
      Width = 551
      Height = 175
      Align = alClient
      BorderOuter = fsNone
      TabOrder = 0
      object RzLabel3: TRzLabel
        Left = 301
        Top = 93
        Width = 39
        Height = 15
        Caption = 'Jumlah'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel4: TRzLabel
        Left = 301
        Top = 65
        Width = 42
        Height = 15
        Caption = 'Tanggal'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel2: TRzLabel
        Left = 301
        Top = 38
        Width = 40
        Height = 15
        Caption = 'No. Ref.'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel11: TRzLabel
        Left = 381
        Top = 38
        Width = 3
        Height = 15
        Caption = ':'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel12: TRzLabel
        Left = 381
        Top = 65
        Width = 3
        Height = 15
        Caption = ':'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel13: TRzLabel
        Left = 381
        Top = 93
        Width = 3
        Height = 15
        Caption = ':'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel7: TRzLabel
        Left = 13
        Top = 11
        Width = 58
        Height = 15
        Caption = 'Kas / Bank'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel8: TRzLabel
        Left = 93
        Top = 11
        Width = 3
        Height = 15
        Caption = ':'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object LKas: TRzLabel
        Left = 561
        Top = 29
        Width = 25
        Height = 15
        Caption = 'LKas'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object LID: TRzLabel
        Left = 569
        Top = 45
        Width = 17
        Height = 15
        Caption = 'LID'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object RzLabel1: TRzLabel
        Left = 13
        Top = 38
        Width = 26
        Height = 15
        Caption = 'Oleh'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel6: TRzLabel
        Left = 93
        Top = 38
        Width = 3
        Height = 15
        Caption = ':'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object LKontak: TRzLabel
        Left = 561
        Top = 61
        Width = 43
        Height = 15
        Caption = 'LKontak'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object LKasTransir: TRzLabel
        Left = 601
        Top = 29
        Width = 64
        Height = 15
        Caption = 'LKasTransir'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object LAkunCA: TRzLabel
        Left = 601
        Top = 45
        Width = 46
        Height = 15
        Caption = 'LAkunCA'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object RzLabel9: TRzLabel
        Left = 93
        Top = 120
        Width = 3
        Height = 15
        Caption = ':'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object RzLabel5: TRzLabel
        Left = 13
        Top = 120
        Width = 56
        Height = 15
        Caption = 'Keperluan'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
      end
      object txtsebesar: TRzNumericEdit
        Left = 393
        Top = 90
        Width = 150
        Height = 23
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        FrameHotTrack = True
        FrameVisible = True
        ParentFont = False
        ReadOnlyColor = clYellow
        TabOnEnter = True
        TabOrder = 5
        OnExit = txtsebesarExit
        IntegersOnly = False
        DisplayFormat = '#,#0.##'
      end
      object txtreferensi: TRzEdit
        Left = 392
        Top = 35
        Width = 150
        Height = 23
        Color = clYellow
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        FrameHotTrack = True
        FrameVisible = True
        ParentFont = False
        ReadOnly = True
        ReadOnlyColor = clYellow
        TabOnEnter = True
        TabOrder = 3
      end
      object txtkas: TRzButtonEdit
        Left = 104
        Top = 8
        Width = 439
        Height = 23
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        FrameHotTrack = True
        FrameVisible = True
        ParentFont = False
        TabOnEnter = True
        TabOrder = 0
        OnKeyPress = txtkasKeyPress
        AllowKeyEdit = False
        OnButtonClick = txtkasButtonClick
      end
      object txtkontak: TRzButtonEdit
        Left = 104
        Top = 35
        Width = 185
        Height = 23
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        FrameHotTrack = True
        FrameVisible = True
        ParentFont = False
        TabOnEnter = True
        TabOrder = 1
        OnKeyPress = txtkontakKeyPress
        AllowKeyEdit = False
        OnButtonClick = txtkontakButtonClick
      end
      object txtterbilang: TRzMemo
        Left = 104
        Top = 62
        Width = 185
        Height = 51
        TabStop = False
        Color = clBtnFace
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        FrameHotTrack = True
        FrameVisible = True
      end
      object cbapprove: TRzCheckBox
        Left = 555
        Top = 91
        Width = 97
        Height = 17
        Caption = 'Aprrove'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        HotTrack = True
        ParentFont = False
        State = cbUnchecked
        TabOrder = 7
        Visible = False
      end
      object cbcair: TRzCheckBox
        Left = 555
        Top = 107
        Width = 97
        Height = 17
        Caption = 'Cair'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        HotTrack = True
        ParentFont = False
        State = cbUnchecked
        TabOrder = 8
        Visible = False
      end
      object cbcancel: TRzCheckBox
        Left = 555
        Top = 123
        Width = 97
        Height = 17
        Caption = 'Cancel'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        HotTrack = True
        ParentFont = False
        State = cbUnchecked
        TabOrder = 9
        Visible = False
      end
      object txtkeperluan: TRzEdit
        Left = 104
        Top = 117
        Width = 439
        Height = 23
        Color = clWhite
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        FrameHotTrack = True
        FrameVisible = True
        ParentFont = False
        ReadOnlyColor = clYellow
        TabOnEnter = True
        TabOrder = 6
      end
      object dtptanggal: TcxDateEdit
        Left = 392
        Top = 62
        EditValue = 0d
        ParentFont = False
        Properties.DateButtons = [btnClear, btnNow, btnToday]
        Properties.DateOnError = deToday
        Properties.InputKind = ikMask
        Style.Font.Charset = ANSI_CHARSET
        Style.Font.Color = clWindowText
        Style.Font.Height = -13
        Style.Font.Name = 'Calibri'
        Style.Font.Style = []
        Style.IsFontAssigned = True
        TabOrder = 4
        OnExit = dtptanggalExit
        Width = 150
      end
    end
    object RzPanel2: TRzPanel
      Left = 1
      Top = 199
      Width = 551
      Height = 41
      Align = alBottom
      BorderOuter = fsNone
      TabOrder = 1
      DesignSize = (
        551
        41)
      object BtnRekam: TRzBitBtn
        Left = 466
        Top = 8
        Anchors = [akTop, akRight]
        Caption = 'Simpan'
        Color = 12615680
        Font.Charset = ANSI_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        OnClick = BtnRekamClick
      end
      object BtnBatal: TRzBitBtn
        Left = 386
        Top = 8
        Anchors = [akTop, akRight]
        Caption = 'Batal'
        Color = 12615680
        Font.Charset = ANSI_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Calibri'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        OnClick = BtnBatalClick
      end
    end
  end
  object Q1: TZQuery
    Connection = DM.con
    Params = <>
    Left = 17
    Top = 88
  end
end
