object Frm_Login: TFrm_Login
  Left = 428
  Top = 243
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Enter name and password'
  ClientHeight = 221
  ClientWidth = 415
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Calibri'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 15
  object RzLabel1: TRzLabel
    Left = 145
    Top = 124
    Width = 31
    Height = 15
    Caption = 'Name'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Calibri'
    Font.Style = []
    ParentFont = False
    Transparent = True
    Layout = tlCenter
    LightTextStyle = True
    ShadowDepth = 1
  end
  object RzLabel2: TRzLabel
    Left = 145
    Top = 153
    Width = 54
    Height = 15
    Caption = 'Password'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Calibri'
    Font.Style = []
    ParentFont = False
    Transparent = True
  end
  object LMessage: TRzLabel
    Left = 144
    Top = 72
    Width = 265
    Height = 49
    AutoSize = False
    Caption = 'LMessage'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Calibri'
    Font.Style = []
    ParentFont = False
    Transparent = True
    WordWrap = True
    BlinkColor = clRed
  end
  object RzLabel5: TRzLabel
    Left = 209
    Top = 124
    Width = 3
    Height = 15
    Caption = ':'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Calibri'
    Font.Style = []
    ParentFont = False
    Transparent = True
    Layout = tlCenter
    LightTextStyle = True
    ShadowDepth = 1
  end
  object RzLabel6: TRzLabel
    Left = 209
    Top = 153
    Width = 3
    Height = 15
    Caption = ':'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Calibri'
    Font.Style = []
    ParentFont = False
    Transparent = True
  end
  object RzPanel2: TRzPanel
    Left = 0
    Top = 0
    Width = 415
    Height = 65
    Align = alTop
    BorderOuter = fsNone
    Color = 16744448
    TabOrder = 0
    object RzLabel3: TRzLabel
      Left = 8
      Top = 8
      Width = 201
      Height = 33
      Caption = 'Login to Database'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -27
      Font.Name = 'Calibri'
      Font.Style = [fsBold, fsItalic]
      ParentFont = False
    end
    object RzLabel4: TRzLabel
      Left = 8
      Top = 40
      Width = 142
      Height = 15
      Caption = 'Enter name and password'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
    end
  end
  object txtPassword: TRzEdit
    Left = 224
    Top = 150
    Width = 185
    Height = 23
    CharCase = ecLowerCase
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Calibri'
    Font.Style = []
    FocusColor = clInfoBk
    FrameHotTrack = True
    FrameVisible = True
    ParentFont = False
    PasswordChar = '*'
    TabOrder = 2
    OnKeyDown = txtPasswordKeyDown
  end
  object txtuser: TRzEdit
    Left = 224
    Top = 121
    Width = 185
    Height = 23
    CharCase = ecLowerCase
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Calibri'
    Font.Style = []
    FocusColor = clInfoBk
    FrameHotTrack = True
    FrameVisible = True
    ParentFont = False
    ReadOnlyColor = clYellow
    TabOnEnter = True
    TabOrder = 1
  end
  object RzPanel1: TRzPanel
    Left = 0
    Top = 180
    Width = 415
    Height = 41
    Align = alBottom
    BorderOuter = fsNone
    TabOrder = 3
    object BtnCancel: TRzBitBtn
      Left = 256
      Top = 8
      Caption = 'Cancel'
      Color = 12615680
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnClick = BtnCancelClick
      ImageIndex = 1
      Layout = blGlyphTop
    end
    object BtnLogin: TRzBitBtn
      Left = 336
      Top = 8
      Caption = 'Ok'
      Color = 12615680
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Calibri'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = BtnLoginClick
      ImageIndex = 0
      Layout = blGlyphTop
    end
  end
  object Q1: TZQuery
    Connection = DM.con
    SQL.Strings = (
      'select * from tbl_user where status=1 order by Namauser')
    Params = <>
    Left = 320
    Top = 56
  end
end
